name: Testing con pytest

on: 
  push: 
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verificar archivo
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/main.py"]; then
            echo "No se encontró main.py."
            exit 1
          fi
          echo "Se encontró main.py"

      - name: Instalar uv
        run: pip install uv; uv venv

      - name: Instalar dependencias con uv
        run: uv pip install fastapi requests pytest httpx

      - name: Test con Pytest
        run: |
          source .venv/bin/activate
          pytest -v